### ISSUE TITLE
Contenu session Simon puis Matthias

### ISSUE THREAD

**Issue by mattlev2** [gabays/Cours_COSME_2019#10]
Ci dessous une liste des balises et fonctions proposées pour l'après-midi. À débattre pour le XSLT:

1. ``xsl:choose``
2. ``xsl:if``
3. ``xsl:variable``: pour travailler avec le teiHeader et y récupérer des infos qu'on injecte dans le corps du texte, en marge ou autre, c'est le plus simple je crois. 
4. la gestion des espaces: c'est compliqué, mais dire quelque chose de ``xsl:strip-space`` ? 
5. Un truc un peu différent mais qui peut servir: ``xsl:result-document``, pour créer plusieurs documents de sortie différents

Peut-on proposer aussi des fonctions xpath ? Ce qui me vient en tête:

1. ``translate()``
2. ``upper|lower-case``
3. ``collection()``, qui est un peu avancée et permet de travailler sur plusieurs fichiers indépendants
4. ``count()`` (vs ``xsl:number``)
5. ``concat()``
6. ``substring-before|after()``
7. ``ends-with()``
8. ``contains()``

**Comment by gabays** [comment]
Donc.
1. Je me propose de faire ```xml:choose```. ```xsl:if```ça va avec.
2. Une première fonction XPath,
2. On ne fait pas XML->XML c'est ça? Parce que sinon on pourrait reprendre mon script ```addingChoices.xsl```en fait: c'est exactement ce programme

**Comment by mattlev2** [comment]
3)  je pense qu'on doit se centrer sur XML vers HTML d'abord. Si on a du temps, on peut préparer du XML vers XML, au cazou. 

Je peux faire ``xsl:variable``, c'est une fonction qu'il faut voir plutôt à la fin de la journée je pense... Et du coup on lie ça avec une fonction xpath du genre translate ou concat (pour récupérer une balise du teiHeader par son ``xml:id``)

**Comment by gabays** [comment]
Oui, et il faudrait jouer avec le doc en mettant des ```xsl:apply-templates select``` ou des ```xsl:value-of``` dans ``` <xsl:template match="/">```. Ca permet de bien voir le fonctionnement d'un doc xslt, par exemple pour changer l'ordre des données du teiHeader?

Il faut aussi faire des notes. C'est important.

**Comment by mattlev2** [comment]
> Oui, et il faudrait jouer avec le doc en mettant des ``xsl:apply-templates`` select

Oui ! À ce propos, @ArianePinche  y a pas un attribut XSL du genre "exclude" pour exclure certaines règles ? je crois avoir utilisé ça y a pas si longtemps mais aucun moyen de m'en souvenir (désolé pour le poke intempestif)

**Comment by mattlev2** [comment]
ps: on peut éditer les message les uns les autres, hésitez pas à commenter sur ma liste ou l'amender directement si plus lisible

**Comment by ArianePinche** [comment]
Pourquoi pas, mais a-t-on le temps ?
Ceci dis, on peut faire une ouverture de séance avec commentaires de code,
avant d'enchainer sur l'exercice XML vers HTML. C'est formateur.

Le mer. 3 avr. 2019 à 19:41, Simon Gabay <notifications@github.com> a
écrit :

**Comment by ArianePinche** [comment]
Oui, ça marche bien avec le concatenage de chaine de caractères

**Comment by ArianePinche** [comment]
Pour le exclude, c'est un attribut XML TEI pour les ODD pour sûr. Mais je
ne l'ai jamais utilisé en XSL. Je joue sur les modes et le select
d'apply-templates. Pour supprimer des éléments je fais une règle vide.

**Comment by gabays** [comment]
Je me lance dans le XSLT step 2. J'espère finir ajd et je passe le relais à Matthias?

**Comment by mattlev2** [comment]
Très bien, j'ai commencé à travailler un peu sur les variables et concat/translate. @gabays tu t'occupes de l'exercice sur les notes ?

**Comment by gabays** [comment]
Wesh khouia. J'ai fait un premier push d'un brouillon de cours. Tu me dis si ça colle avec ton truc? C'est un peu *short* mais je veux pas te manger ton *Lebensraum*…

**Comment by mattlev2** [comment]
Ça me paraît bien, continue. Et au pire si nos trucs se chevauchent trop on fait la session de l'après midi ensemble.

**Comment by ArianePinche** [comment]
J'ai regardé vos documents, ça me parait super bien :).
J'ai vu quelques coquilles : 
- Step 2
 - I.a : il manque un -s à caractères
 - Exercice I.a : il y a andromsque au lieu de andromaque
- Partie 3
- Attention pour translate, autour de la chaine de caractère initiale, il manque les ' ' pour signifier que c'est une chaine de caractères. Peut-être faudrait-il l'appeler autrement pour bien la différencier des deux autres, comme chaine à transformer ou pattern. 
- Dans l'xsl, ligne 102 du code, il y a une persName, est-ce normal ? je mettrai plutôt le masculin.
Bonne journée :)

**Comment by mattlev2** [comment]
J'ai essayé de corriger ce que tu m'as signalé. 
@gabays, est-ce que ton 2nd xsl est une incrémentation du premier ? Si ce n'est pas le cas, tu peux créer une xsl qui contienne tous les points que tu abordes, que je puisse reprendre et enrichir à mon tour ?

**Comment by gabays** [comment]
De retour après problèmes administratifs:

1. Oui, je reprends le truc d'Ariane et je rajoute des trucs. Ca me semble être mieux vu qu'on bosse sur un même texte, non?
2. Coquille: Les variables sont appelées à l'aide du caractère*s* dollar '$'.
3. Je vais copier ta mise en page pour les fonctions XPath
4. Les notes je ne sais pas si on va les utiliser: elles sont dans le ```back```… Ou alors j'en mets qq unes dans le corps du texte pour les traiter et je leur fait faire des pop-ups?
5. Y'a plus de flash fluo Matthias…
6. Avec les noms, il n'y a qu'un lien wikipedia: "Référence_s_" n'a pas besoin d'être au pluriel

(J'update les questions au fur et à mesure qu'elles me viennent à l'esprit: vous recevez un mail à chaque fois?)

**Comment by mattlev2** [comment]
Non, t'inquiète, on reçoit que le lien à la création de la réponse. 
1) Ok super. Du coup je reprendrai ta xsl et je ferai du copier-coller avec mes apports.   
2) Je vais voir ça. Fait 

iv) si tu veux tu ajoutes un point dans ma partie, c'est un peu avancé non ? 
v) je vais essayer de remédier à ça
vi) je vais corriger. Fait. 


Il faudra à un moment ou à un autre renommer les fichiers, les dossiers, pour faire un truc plus propre. @gabays , j'ai commencé à donner le lien à des personnes, tu as mis en confidentiel les issues ?

**Comment by gabays** [comment]
Rien de confidentiel. We walk under the sun.
Concernant les notes, tu avais demandé si je les faisais… Comme je suis un bon garçon…
En fait, on veut pas faire un pop up plutôt qu'un lien vers le header pour la déf des personnes?

**Comment by mattlev2** [comment]
1) Mouais. 
2) Très bien !
3) Si, on peut, mais ça fait du css + du javascript en plus, et ça peut parasiter l'enseignement principal qui doit être du XSL (en gros je suis plutôt contre)

**Comment by gabays** [comment]
1. Je croyais qu'on pouvait avec GitLab, mais qu'avec GitHub l'option _private_ était payante… Si tu me dis où c'est (un rapide tour sur le net ne m'a rien appris) je mets ça en confidentiel.
2. Pour les notes en popup, je les ai mises avec tooltip pour la raison que tu mentionnes: 0 javascript, tout est dans le CSS.
```XML
<xsl:template match="note">
    <span class="tooltip">
        <img src="img_413193.png" height="10"/>
        <span class="tooltiptext">
            <xsl:apply-templates select="text()|title|ref"/>
        </span>
    </span> 
</xsl:template>
```
et 
```CSS
/* Tooltip container */
.tooltip {
  position: relative;
  display: inline-block;
  border-bottom: 1px dotted black; /* If you want dots under the hoverable text */
}

/* Tooltip text */
.tooltip .tooltiptext {
  visibility: hidden;
  width: 120px;
  background-color: #555;
  color: #fff;
  text-align: center;
  padding: 5px 0;
  border-radius: 6px;

  /* Position the tooltip text */
  position: absolute;
  z-index: 1;
  bottom: 125%;
  left: 50%;
  margin-left: -60px;

  /* Fade in tooltip */
  opacity: 0;
  transition: opacity 0.3s;
}

/* Tooltip arrow */
.tooltip .tooltiptext::after {
  content: "";
  position: absolute;
  top: 100%;
  left: 50%;
  margin-left: -5px;
  border-width: 5px;
  border-style: solid;
  border-color: #555 transparent transparent transparent;
}

/* Show the tooltip text when you mouse over the tooltip container */
.tooltip:hover .tooltiptext {
  visibility: visible;
  opacity: 1;
} 

```
